title: "X, Y and Z Axes in BlocksCAD"
hero_image: images/banner.png
description: "X, Y and Z Axes in BlocksCAD"
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
version: 1
listed: false
ingredient: true
copyedit: false
last_tested: "2018-03-28"
curriculum: creator, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: "blockscad, 3D printing"
hardware: ""
software: "blockscad
site_areas:
steps:
  - title: Axes in BlocksCAD
